"""Add new tables

Revision ID: 3d388d546010
Revises: eae0e050448f
Create Date: 2026-06-05 13:44:05.855815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d388d546010'
down_revision: Union[str, Sequence[str], None] = 'eae0e050448f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propuestas',
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iniciativa_id')
    )
    op.create_table('componentes_documentales',
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('contenido', sa.String(length=4096), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('propuesta_id', sa.Integer(), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['padre_id'], ['componentes_documentales.id'], ),
    sa.ForeignKeyConstraint(['propuesta_id'], ['propuestas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('iniciativas', sa.Column('creador_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'iniciativas', 'ciudadanos', ['creador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'iniciativas', type_='foreignkey')
    op.drop_column('iniciativas', 'creador_id')
    op.drop_table('componentes_documentales')
    op.drop_table('propuestas')
    # ### end Alembic commands ###
