"""Initial migration

Revision ID: eae0e050448f
Revises: 
Create Date: 2026-06-05 12:33:02.183991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae0e050448f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudadanos',
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudadanos_dni'), 'ciudadanos', ['dni'], unique=True)
    op.create_index(op.f('ix_ciudadanos_email'), 'ciudadanos', ['email'], unique=True)
    op.create_table('iniciativas',
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('descripcion', sa.String(length=4096), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'SELLADA', 'ENVIADA', name='estadoiniciativaenum'), nullable=False),
    sa.Column('total_firmas', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.Column('sellado_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmas',
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('es_valida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ciudadano_id', 'iniciativa_id', name='uq_firma_ciudadano_iniciativa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firmas')
    op.drop_table('iniciativas')
    op.drop_index(op.f('ix_ciudadanos_email'), table_name='ciudadanos')
    op.drop_index(op.f('ix_ciudadanos_dni'), table_name='ciudadanos')
    op.drop_table('ciudadanos')
    # ### end Alembic commands ###
